name = "pgb1_perf_test"
description = ""
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["pgb1_perf_test"]

[[depends-on]]
tresses = "~0.1.0"
pgb1 = "*"

[[pins]]
tresses = { path='..' }
pgb1 = { path = "../../pgb1-ada-sdk" }
rp2040_hal = { path = "../../rp2040_hal" }

# [configuration.values]
# tresses.Resources_Linker_Section = ".time_critical.tresses_resources"
# tresses.Code_Linker_Section = ".time_critical.tresses_code"
